#!/bin/bash


USAGE="$(basename $0)\t[-h|-u] reponame"

function show_usage() {
    echo -e ${USAGE}
}

function show_help() {
    echo -e ${USAGE}
    echo -e "\treponame\t\tname of the repo to create"
    echo -e "\t-h\t\tshow help"
    echo -e "\t-u\t\tshow usage"
    echo
}

while getopts "hu" opt; do
    case "$opt" in
        h)
            show_help
            exit 0
            ;;
        u)
            show_usage
            exit 0
            ;;
    esac
done


if [[ $# != 1 ]]; then
    show_usage
    exit 0
fi

read -p "creer le depot '$1'? [Y/N] " answer
if [ "`echo $answer | cut -c1`" != "Y" ]; then exit 1; fi


token=`python2 -c "import hashlib; import getpass; print(hashlib.sha512((getpass.getpass().decode('utf8'))).hexdigest())"`

blih.py -u $BLIH_USER -t $token repository create $1 || exit 1
blih.py -u $BLIH_USER -t $token repository setacl $1 ramassage-tek r || exit 1
blih.py -u $BLIH_USER -t $token repository setacl $1 rush r || exit 1
read -p 'add other users? ' users
for i in $users
do
  blih.py -u $BLIH_USER -t $token repository setacl $1 $i rw;
done

echo
echo repo $1 created.
echo 'ACL rights:'
blih.py -u $BLIH_USER -t $token repository getacl $1 || exit 1

echo 

read -p "cloner le depot ? [Y/N]" answer
if [ "`echo $answer | cut -c1`" != "Y" ]; then exit 0; fi
git clone $BLIH_USER@git.epitech.eu:/$BLIH_USER/$1

