#!/bin/bash


USAGE="$(basename $0)\treponame"

function show_usage() {
    echo -e ${USAGE}
}

function show_help() {
    echo -e ${USAGE}
    echo -e "\treponame\t\tname of the repo to create"
    echo -e "\t-h\t\tshow help"
    echo -e "\t-u\t\tshow usage"
    echo
}

while getopts "hu" opt; do
    case "$opt" in
        h)
            show_help
            exit 0
            ;;
        u)
            show_usage
            exit 0
            ;;
    esac
done


if [[ $# != 1 ]]; then
    show_usage
    exit 0
fi

read -p "Create Repository '$1' ? [y/n] " answer
if [ "`echo $answer | cut -c1`" != "y" ]; then exit 1; fi

blih -u $BLIH_USER repository create $1 || exit 1
blih -u $BLIH_USER repository setacl $1 ramassage-tek r || exit 1
read -p 'Add new users to the projet ? ' users
for i in $users
do
  blih -u $BLIH_USER repository setacl $1 $i rw;
done

echo
echo repo $1 created.
echo 'ACL rights:'
blih -u $BLIH_USER repository getacl $1 || exit 1

echo 

read -p "Clone Repository '$1' ? [y/n]" answer
if [ "`echo $answer | cut -c1`" != "y" ]; then exit 0; fi
git clone git@git.epitech.eu:/$BLIH_USER/$1

