#!/bin/bash

function show_usage() {
    echo -e 'oi2b commands:\n'
    find $OI2B_HOME -maxdepth 1 -not -name oi2b -executable -type f -exec bash {} -u \;
}

function show_help() {
    echo -e 'oi2b commands:\n'
    find $OI2B_HOME -maxdepth 1 -not -name oi2b -executable -type f -exec bash {} -h \;
}



function main {
    OI2B_HOME=${OI2B_HOME:-${HOME}/.bin/oi2b.git/}
    BLIH_USER=${BLIH_USER:-$USER}

    # TODO: ssh key upload / generation / management
    BLIH_SSH_KEY=${BLIH_SSH_KEY:-$"???"}

    while getopts "hu" opt; do
        case "$opt" in
            h)
                local option='help'
                ;;
            u)
                local option='usage'
                ;;
        esac
    done


    if [ "$#" -ge 1 ] ; then
        if [[ -x ${OI2B_HOME}/$1 ]]; then
            /bin/bash ${OI2B_HOME}/$1 "${@:2}"
            return $?
        else
            echo "$0: module not found \"$1\""
        fi
    fi

    if [[ -z "$option" || $option == "usage" ]]; then
        show_usage
    else [[ $option == 'help' ]]
        show_help
    fi
    return 0
}

main $@

# finish by forwarding status of called module
exit $?
